# Generated by Django 5.0.1 on 2024-01-19 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_likes',
        ),
        migrations.AddField(
            model_name='review',
            name='user_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviews_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
